In [1]:
import numpy as np
import random
import pygame
from itertools import combinations 

env_y = 10
env_x = 10
env_z = 15
env_state_space = np.ones((env_z, env_y, env_x))
env_state_space = np.negative(env_state_space)

y_bound = env_y - 1
x_bound = env_x - 1

#env_term_state = [(0,0), (y_bound,0), (0,x_bound), (y_bound,x_bound)]

env_term_state = [(1,1), (5,2), (2,7), (9,6)]

all_term_states = []
for arrangements in range(4,0,-1):
    all_term_states.append(list(combinations(env_term_state, arrangements)))

formatted_term_list = []
for combos in all_term_states:
    for goal_points in combos:
        formatted_term_list.append(goal_points)
        
unique_states = 0
for points in formatted_term_list:
    for point in points:
        env_state_space[unique_states,point[0],point[1]] = 50
    unique_states += 1

goals_to_achieve = env_term_state[:]
    
print(env_state_space[0])
print(env_state_space[1])
print("Co-ordinates of goal states")
print(env_term_state)
print("State Space Goal groupings")
for item in formatted_term_list:
    print(item )
print("State Space: ", env_state_space.shape)

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
[[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. 50. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. 50. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. 50. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. 50. -1. -1. -1.]]
[[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. 50. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. 50. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. 50. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]]
Co-ordinates of goal states
[(1, 1), (5, 2), (2, 7), 

# Movement Code of the Environment

In [2]:
def move(state,action):
    # (y,x)
    
    switch = {
        0: up,
        1: right,
        2: down,
        3: left
    }

    func = switch.get(action, lambda: "Invalid action")
    new_state = func(state)
    return new_state

#make sure moves are within a bound
def valid_move(state):
    
    if state[0] > y_bound:
        state = (state[0]-1, state[1])
    elif state[0] < 0:
        state = (state[0]+1, state[1])
        
    if state[1] > x_bound:
        state = (state[0], state[1] - 1)
    elif state[1] < 0:
        state = (state[0], state[1] + 1)
    
    return state
    
def up(state):
    new_state = (state[0] - 1, state[1])
    new_state = valid_move(new_state)
    return new_state

def right(state):
    new_state = (state[0], state[1] + 1)
    new_state = valid_move(new_state)
    return new_state
    
def down(state):
    new_state = (state[0] + 1, state[1])
    new_state = valid_move(new_state)
    return new_state
    
def left(state):
    new_state = (state[0], state[1] - 1)
    new_state = valid_move(new_state)
    return new_state

# Actual transition of the environment based on action

In [3]:
# def step(state, action):        
    
#     z = state[0]
#     state = (state[1],state[2])
#     #############################here is the issue, need to identify the new state space location
#     if state in formatted_term_list[z]:
#         done = True
#         state_prime = (z, state[0], state[1])
#         reward = 0
        
#     else:
#         done = False
#         state_prime = move(state,action)
        
#         if state_prime in formatted_term_list[z] and len(formatted_term_list[z]) != 1:
            
#             current_set = list(formatted_term_list[z])
#             current_set.remove(state_prime)
            
#             index = 0
#             for item in formatted_term_list:
#                 if list(item) == current_set:
#                     z = index
#                     break
#                 else:
#                     index += 1
        
#         reward = env_state_space[(z, state_prime[0], state_prime[1])]
        
#         state_prime = (z, state_prime[0], state_prime[1])
        
#     return state_prime, reward, done

In [4]:
def step(state, action):        
    
    z = state[0]
    state = (state[1],state[2])
    #############################here is the issue, need to identify the new state space location
    if state in formatted_term_list[z]:
        done = True
        state_prime = (z, state[0], state[1])
        reward = 0
        
    else:
        done = False
        state_prime = move(state,action)
        reward = env_state_space[(z, state_prime[0], state_prime[1])]
        
        state_prime = (z, state_prime[0], state_prime[1])
    return state_prime, reward, done

In [5]:
ACTION_SPACE = list(range(0,4))

print("Action Space:")
print(ACTION_SPACE)
print(["Up", "Right", "Down", "Left"])

Reward = env_state_space

gamma = 1 
significant_improvement = 0.01 

Action Space:
[0, 1, 2, 3]
['Up', 'Right', 'Down', 'Left']


# Q Learning
## _$Q^{new}$($s_{t}$, $a_{t}$)  &larr; (1 - $\alpha$) $\cdot$ Q($s_{t}$, $a_{t}$) + $\alpha$ $\cdot$ ($r_{t}$ + $\gamma$ $\cdot$ $max_{a}$Q($s_{t+1}$, $a$))_

In [6]:
Q = np.zeros((env_z, env_y, env_x,len(ACTION_SPACE))) 
print(Q.shape)

alpha = 0.01
gamma = 1
epsilon = 0.1

done = False

for iteration in range(100):
    for z in range(env_z):
        for y in range(env_y):
            for x in range(env_x):
                s = (z, y, x)      

                while done != True:

                    if random.uniform(0, 1) < epsilon:
                        action = random.choice(ACTION_SPACE)
                    else:
                        action = np.argmax(Q[z,s[1],s[2],:])

                    s_new, rew, done = step(s,action) 
                    old_Q = Q[z,s[1],s[2],action]

                    next_max = np.max(Q[s_new[0], s_new[1], s_new[2], :])

                    Q[z, s[1], s[2], action] = (1 - alpha) * old_Q + alpha * (rew + gamma * next_max)
                    s = s_new

                done = False

(15, 10, 10, 4)


# Trajectory Printing

In [7]:
switch_arrow = {
    0: u"\u2191",
    1: u"\u2192",
    2: u"\u2193",
    3: u"\u2190",
    4: "x"
}

z = 14

print(formatted_term_list[z])
trajectory_grid = ""
for y in range(env_y):
    for x in range(env_x):
        if((y,x) in formatted_term_list[z]):
            trajectory_grid += "x "
        else:
            trajectory_grid += switch_arrow.get(np.argmax(Q[z,y,x,:])) + " "
    trajectory_grid += "\n"
    
        
print(trajectory_grid, "\n")
trajectory_grid = ""

((9, 6),)
↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ ↓ 
↓ ↓ ↓ ↓ ↓ ↓ ↓ ← ← ← 
→ → → → → → ↓ ← ← ← 
↑ ↑ → → → → ↓ ← ← ← 
→ → → → → → ↓ ← ← ← 
→ → → → → → ↓ ← ← ← 
→ → → → → → ↓ ← ← ← 
→ → → → → → ↓ ← ← ← 
→ → → → → → ↓ ← ← ← 
→ → → → → → x ← ← ← 
 



In [13]:
def render(z):
    
    screen.fill(BLACK)
    #z = 0
    for y in range(height):
        for x in range(width):                
            if y == current_state[1] and x == current_state[2]:
                colour = GREEN
            elif env_state_space[z,y,x] != -1:
                colour = RED
            else:
                colour = WHITE

            rect_pos_x = x*(CONSTANT_SIZE+1)+1
            rect_pos_y = y*(CONSTANT_SIZE+1)+1
            rect = pygame.Rect(rect_pos_x, rect_pos_y , CONSTANT_SIZE, CONSTANT_SIZE)
            pygame.draw.rect(screen, colour, rect)


for episode in range(1):
    
    done = False
    reward_total = 0
    goals_to_achieve = env_term_state[:]
    print("GOALS")
    print(goals_to_achieve)
    print(len(goals_to_achieve))
    z = 0
    
    start_y = np.random.randint(low=0, high=env_y)
    start_x = np.random.randint(low=0, high=env_x)
    current_state = (z, start_y, start_x)

    BLACK = (0, 0, 0)
    WHITE = (255, 255, 255)
    GREEN = (0, 255, 0)
    RED = (255, 0, 0)

    pygame.init()
    
    CONSTANT_SIZE = 50
    height = env_y#env_state_space.shape[0]
    width = env_x#env_state_space.shape[1]
    
    size_y = (CONSTANT_SIZE * height) + height + 1
    size_x = (CONSTANT_SIZE * width) + width + 1
    screen_size = (size_x, size_y)

    screen = pygame.display.set_mode(screen_size)

    pygame.display.set_caption("Worseworld")

    session = True

    clock = pygame.time.Clock()
    wait_milli_sec = 200 #350
    
    print("Episode ", episode + 1)
    print("Starting State: ", current_state)
    
    render(z)

    pygame.display.flip()
    pygame.time.wait(wait_milli_sec)    

    while session:

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                pygame.quit()
        
        action = np.argmax(Q[current_state[0],current_state[1],current_state[2],:])
        
        obs, rew, done = step(current_state, action) 
        
        current_state = obs
        z = current_state[0]
        reward_total += rew
    
        if done == True:
            index = 0
            for item in goals_to_achieve:
                if item == (current_state[1], current_state[2]):
                    del goals_to_achieve[index]
                    break
                else:
                    index += 1

            if len(goals_to_achieve) == 0:
                break

            z_index = 0
            for item in formatted_term_list:
                if list(item) == goals_to_achieve:
                    break
                else:
                    z_index += 1

            current_state = (z_index, current_state[1], current_state[2])

            z = z_index
            print("Z: ", z)
            print(len(goals_to_achieve))
            done = False

        render(z)
        
        print("Cumulative Reward: " ,reward_total)

        pygame.display.flip()
        pygame.time.wait(wait_milli_sec)
        clock.tick(60)
        
    print("Ending state: ", current_state)
    
pygame.quit()

GOALS
[(1, 1), (5, 2), (2, 7), (9, 6)]
4
Episode  1
Starting State:  (0, 7, 4)
Cumulative Reward:  -1.0
Cumulative Reward:  -2.0
Cumulative Reward:  -3.0
Cumulative Reward:  47.0
Z:  3
3
Cumulative Reward:  47.0
Cumulative Reward:  46.0
Cumulative Reward:  45.0
Cumulative Reward:  44.0
Cumulative Reward:  43.0
Cumulative Reward:  93.0
Z:  10
2
Cumulative Reward:  93.0
Cumulative Reward:  92.0
Cumulative Reward:  91.0
Cumulative Reward:  90.0
Cumulative Reward:  89.0
Cumulative Reward:  88.0
Cumulative Reward:  87.0
Cumulative Reward:  137.0
Z:  14
1
Cumulative Reward:  137.0
Cumulative Reward:  136.0
Cumulative Reward:  135.0
Cumulative Reward:  134.0
Cumulative Reward:  133.0
Cumulative Reward:  132.0
Cumulative Reward:  131.0
Cumulative Reward:  130.0
Cumulative Reward:  180.0
Ending state:  (14, 9, 6)


In [9]:
pygame.quit()

In [10]:
# print(env_term_state)
# print(goals_to_achieve)
# print("LEN: ", len(goals_to_achieve))

# state = (0, 0)
# print("STATE: ", state)

# index = 0
# for item in goals_to_achieve:
#     if item == state:
#         print(index)
#         del goals_to_achieve[index]
#         break
#     else:
#         index += 1

# z_index = 0
# for item in formatted_term_list:
#     print(list(item))
#     if list(item) == goals_to_achieve:
#         print("Z Index: ", z_index)
#         print(formatted_term_list[z_index])
#         print(goals_to_achieve)
#     else:
#         z_index += 1
        



# print(goals_to_achieve)

In [11]:
#         if done == True:
            
#             if len(goals_to_achieve) == 0:
#                 break
                
#             else:
#                 index = 0
#                 for item in goals_to_achieve:
#                     if item == (current_state[1], current_state[2]):
#                         del goals_to_achieve[index]
#                         break
#                     else:
#                         index += 1
                
# #                 if len(goals_to_achieve) == 0:
#                     break
                
#                 z_index = 0
#                 for item in formatted_term_list:
#                     if list(item) == goals_to_achieve:
#                         break
#                     else:
#                         z_index += 1

#                 current_state = (z_index, current_state[1], current_state[2])
                
#                 z = z_index
#                 print("Z: ", z)
#                 print(len(goals_to_achieve))
#                 done = False