In [122]:
import numpy as np

# (y,x)
x = 3
y = 3
grid = np.ones((y, x))
grid = np.negative(grid)
    
rand_y = np.random.randint(low=0, high=y)
rand_x = np.random.randint(low=0, high=x)
    
grid[rand_y][rand_x] = 10

print(grid.shape)
print(grid)

(3, 3)
[[10. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]


In [123]:
ACTION_SPACE = list(range(0,5))
print(action_space)
# 0 - up
# 1 - right
# 2 - down
# 3 - left
# 4 - pickup

STATES= 90

STATE_SPACE = np.zeros((1, STATES))
print(STATE_SPACE)

V = np.zeros((1, STATES)) 
Pi = np.zeros((1, STATES))  
gamma = 0.9 
significant_improvement = 0.01 

#print(V)

initial_rand_y = np.random.randint(low=0, high=y)
initial_rand_x = np.random.randint(low=0, high=x)
current_state = (initial_rand_y, initial_rand_x)
print(current_state)


iteration = 0
    
#for s in range (0, STATE_SPACE.shape[1]):
#    old_v = V[s]
#    action = best_action_value(s) 
#    env.env.s = s  
#    s_new, rew, done, info = env.step(action) 
#    V[s] = rew + gamma * V[s_new] 
#    Pi[s] = action
#    delta = max(delta, np.abs(old_v - V[s]))
#    state += 1

[0, 1, 2, 3, 4]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
(0, 0)


In [124]:
import random

grid_x = 10
grid_y = 10

y_bound = 9
x_bound = 9

action = 1

def move(state,action):
    # (y,x)
    switch = {
        0: up,
        1: right,
        2: down,
        3: left,
        4: pickup
    }

    func = switch.get(action, lambda: "Invalid action")
    new_state = func(state)
    return new_state

def valid_move(state):
    if state[0] > y_bound:
        state = (state[0]-1, state[1])
    elif state[0] < 0:
        state = (state[0]+1, state[1])
        
    if state[1] > x_bound:
        state = (state[0], state[1] - 1)
    elif state[1] < 0:
        state = (state[0], state[1] + 1)
    
    return state
    
def up(state):
    new_state = (state[0] - 1, state[1])
    new_state = valid_move(new_state)
    return new_state

def right(state):
    new_state = (state[0], state[1] + 1)
    new_state = valid_move(new_state)
    return new_state
    
def down(state):
    new_state = (state[0] + 1, state[1])
    new_state = valid_move(new_state)
    return new_state
    
def left(state):
    new_state = (state[0], state[1] - 1)
    new_state = valid_move(new_state)
    return new_state
    
def pickup(state):
    return state

grid = np.ones((grid_y, grid_x))
pos = (1, 1)
grid[pos[0]][pos[1]] = 10
print(grid)
#render

#for _ in range(5):
#    action = random.choice(ACTION_SPACE)
#    next_pos = move(pos,action)
#    print("Next position")
#    print(next_pos)
#    grid[pos[0]][pos[1]] = 1
#    grid[next_pos[0]][next_pos[1]] = 10
#    print(grid)
#    pos = next_pos
    


[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1. 10.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [125]:
import pygame

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 255, 0)
RED = (255, 0, 0)
 
pygame.init()

CONSTANT_SIZE = 50
height = grid.shape[0]
width = grid.shape[1]

size_y = (CONSTANT_SIZE * height) + height + 1
size_x = (CONSTANT_SIZE * width) + width + 1
screen_size = (size_y, size_x)

screen = pygame.display.set_mode(screen_size)

pygame.display.set_caption("Badworld")
 
session = True

clock = pygame.time.Clock()
 
while session:
    
    
    
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            session = False
 
    screen.fill(BLACK)
    
    for y in range(height):
        for x in range(width):
            if grid[y][x]== 10:
                colour = RED
            else:
                colour = WHITE
            
            rect_pos_x = x*(CONSTANT_SIZE+1)+1
            rect_pos_y = y*(CONSTANT_SIZE+1)+1
            rect = pygame.Rect(rect_pos_x, rect_pos_y , CONSTANT_SIZE, CONSTANT_SIZE)
            pygame.draw.rect(screen, colour, rect)    
    
    action = random.choice(ACTION_SPACE)
    next_pos = move(pos,action)
    #print("Next position")
    #print(next_pos)
    grid[pos[0]][pos[1]] = 1
    grid[next_pos[0]][next_pos[1]] = 10
    #print(grid)
    pos = next_pos
    
    pygame.display.flip()
    pygame.time.wait(250)
    clock.tick(60)

pygame.quit()

In [30]:
pygame.quit()